import { describe, it, expect, beforeEach, vi } from "vitest";
import { Visualizer } from "@/lib/research/visualizer";
import * as ai from "ai";

// Mock the AI SDK
vi.mock("ai", () => ({
  generateObject: vi.fn(),
}));

describe("Visualizer", () => {
  let visualizer: Visualizer;

  beforeEach(() => {
    visualizer = new Visualizer();
    vi.clearAllMocks();
    process.env.GOOGLE_GENERATIVE_AI_API_KEY = 'test-key';
  });

  afterEach(() => {
    delete process.env.GOOGLE_GENERATIVE_AI_API_KEY;
  });

  describe("validate", () => {
    it("should validate a correct markdown table", () => {
      const table = "| Header 1 | Header 2 |\n|----------|----------|\n| Cell 1   | Cell 2   |";
      expect(visualizer.validate(table, "table")).toBe(true);
    });

    it("should fail an incorrect markdown table (missing separator)", () => {
      const table = "| Header 1 | Header 2 |\n| Cell 1 | Cell 2 |";
      expect(visualizer.validate(table, "table")).toBe(false);
    });

    it("should validate a correct mermaid flowchart", () => {
      const chart = "flowchart TD\n  A --> B";
      expect(visualizer.validate(chart, "mermaid")).toBe(true);
    });

    it("should validate a correct mermaid pie chart", () => {
      const chart = "pie title Pets\n  \"Dogs\" : 386\n  \"Cats\" : 85";
      expect(visualizer.validate(chart, "mermaid")).toBe(true);
    });

    it("should fail an incorrect mermaid chart type", () => {
      const chart = "unknownChart TD\n  A --> B";
      expect(visualizer.validate(chart, "mermaid")).toBe(false);
    });

    it("should fail for empty code", () => {
      expect(visualizer.validate("", "mermaid")).toBe(false);
      expect(visualizer.validate("   ", "table")).toBe(false);
    });
  });

  describe("process", () => {
    it("should return an empty array for short text", async () => {
      const result = await visualizer.process("Too short");
      expect(result).toEqual([]);
    });

    it("should return visualizations generated by LLM", async () => {
      const mockVisualizations = [
        {
          type: "mermaid",
          chartType: "bar",
          rawData: { values: [10, 20] },
          code: "graph TD; A-->B",
          citations: [],
          caption: "Growth Chart",
          confidence: 0.9,
        },
      ];

      (ai.generateObject as any).mockResolvedValue({
        object: { visualizations: mockVisualizations },
      });

      const result = await visualizer.process(
        "Company A grew by 10% in 2021 and 20% in 2022. This is a significant trend that needs visualization."
      );

      expect(result).toHaveLength(1);
      expect(result[0].caption).toBe("Growth Chart");
      expect(result[0].id).toBeDefined();
    });

    it("should filter out low confidence visualizations", async () => {
      const mockVisualizations = [
        {
          type: "mermaid",
          chartType: "bar",
          rawData: {},
          code: "...",
          citations: [],
          caption: "Low Confidence",
          confidence: 0.5,
        },
      ];

      (ai.generateObject as any).mockResolvedValue({
        object: { visualizations: mockVisualizations },
      });

      const result = await visualizer.process("Some long enough text to trigger processing. This text is long enough now.");
      expect(result).toHaveLength(0);
    });
  });
});